# Generated by Django 4.1.6 on 2023-02-14 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=244, null=True)),
                ('description', models.TextField(null=True)),
                ('bill', models.CharField(max_length=244, null=True)),
                ('balance', models.CharField(choices=[('profit', 'profit'), ('expense', 'expense'), ('sale', 'sale'), ('cashed', 'cashed')], max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=244, null=True)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(choices=[('qty', 'QTY'), ('mtr', 'MTR'), ('len', 'LEN')], default='LEN', max_length=7, null=True)),
                ('sale_price', models.CharField(max_length=244, null=True)),
                ('purchase_price', models.CharField(max_length=244, null=True)),
                ('stock', models.CharField(max_length=244, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=244, null=True)),
                ('last_name', models.CharField(max_length=244, null=True)),
                ('email', models.CharField(max_length=244, null=True)),
                ('address', models.CharField(max_length=244, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.CharField(max_length=244, null=True)),
                ('sale_bill', models.CharField(max_length=244, null=True)),
                ('purchase_bill', models.CharField(max_length=244, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(null=True)),
                ('sale', models.CharField(max_length=244, null=True)),
                ('purchase', models.CharField(max_length=244, null=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person')),
                ('products', models.ManyToManyField(to='core.orderproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
