# Generated by Django 4.1.6 on 2023-12-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_order_creator_alter_order_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='special_field',
            field=models.CharField(default='null', max_length=244, null=True),
        ),
    ]
